# jobs domain to mcd job query
[[redirects]]
from = "https://jobs.mcdonalds-nordheide.de/*"
to = "https://karriere.mcdonalds.de/jobangebote/?location=21244%2C+Buchholz+in+der+Nordheide+-+Buchholz&distance=15"
force = true
status = 302

[[redirects]]
from = "/job*"
to = "https://karriere.mcdonalds.de/jobangebote/?location=21244%2C+Buchholz+in+der+Nordheide+-+Buchholz&distance=15"
force = true
status = 302


# index page to the restaurant list
[[redirects]]
from = "/"
to = "https://www.mcdonalds.de/restaurants-nordheide"
# to = "https://www.unserebroschuere.de/petersen-hanson-familienrestaurants/WebView/"
force = true
status = 302

[[redirects]]
from = "/index.html"
to = "https://www.mcdonalds.de/restaurants-nordheide"
# to = "https://www.unserebroschuere.de/petersen-hanson-familienrestaurants/WebView/"
force = true
status = 302

# everything else to the restaurant list (unless it exists on netlify)
[[redirects]]
from = "/*"
to = "https://www.mcdonalds.de/restaurants-nordheide"
# to = "https://www.unserebroschuere.de/petersen-hanson-familienrestaurants/WebView/"
status = 302
